[versions]
annotations = "23.0.0"

spigot = "1.16.5-R0.1-SNAPSHOT"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

spigot = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }